### PR TITLE
Protect system and user dirs used for daemon

### LINKED ISSUE #82: Restart loop when `/data` is read-only
NervesSSH got into a restart loop when after failing to create a host key, but couldn't due to `/data` not being writable. The problem is the `system_dir` parameter below needs to be adjusted when this happens. I got this when I forgot to enable `f2fs` support in the Linux kernel options. I could imagine this is possible to get many other ways, but disabling or misspelling the data partition filesystem type seems the easiest way to reproduce at the moment.

```
00:00:00.129 [warn]  [NervesSSH] Failed to write generated SSH host key to /data/nerves_ssh/ssh_host_ed25519_key - {:error, :erofs}

The SSH daemon wil continue to run and use the generated key, but a new host key
will be generated the next time the daemon is started.


00:00:00.134 [error] [NervesSSH] :ssd.daemon failed: {:error, {:eoptions, {{:system_dir, '/data/nerves_ssh'}, :enoent}}}

00:00:00.636 [error] [NervesSSH] terminating with reason: {:ssh_daemon_error, {:error, {:eoptions, {{:system_dir, '/data/nerves_ssh'}, :enoent}}}}

00:00:00.637 [error] GenServer NervesSSH terminating
** (stop) {:ssh_daemon_error, {:error, {:eoptions, {{:system_dir, '/data/nerves_ssh'}, :enoent}}}}
Last message: {:continue, :start_daemon}
State: %NervesSSH.State{opts: %NervesSSH.Options{authorized_keys: [], daemon_option_overrides: [pwdfun: &CircuitsQuickstart.ssh_check_pass/2, auth_method_kb_interactive_data: &CircuitsQuickstart.ssh_show_prompt/3], decoded_authorized_keys: [], exec: :elixir, iex_opts: [dot_iex_path: "/etc/iex.exs"], port: 22, shell: :elixir, subsystems: [{'fwup', {SSHSubsystemFwup, [devpath: "/dev/mmcblk0"]}}, {'sftp', {:ssh_sftpd, [cwd: '/']}}], system_dir: "/data/nerves_ssh", user_dir: "/data/nerves_ssh/default_user", user_passwords: []}, sshd: nil, sshd_ref: nil}

00:00:00.661 [warn]  [NervesSSH] Failed to save authorized_keys file: {:error, :enoent}

00:00:00.679 [warn]  [NervesSSH] Failed to write generated SSH host key to /data/nerves_ssh/ssh_host_ed25519_key - {:error, :erofs}

The SSH daemon wil continue to run and use the generated key, but a new host key
will be generated the next time the daemon is started.


00:00:00.682 [error] [NervesSSH] :ssd.daemon failed: {:error, {:eoptions, {{:system_dir, '/data/nerves_ssh'}, :enoent}}}
```

### PR DESCRIPTION
**Pull request by jjcarstens**
Fixes #82

In some cases, the filesystem may not be up (or not working) and could case errors
when trying to generate the host key or do anything with the fs. The hope here is
that at least a tmpfs will be up and to try that instead of crashing everything
since Erlang `:ssh` module requires the `system_dir` and `user_dir` option and
there seems to be no way around that (yet?)

### CODE REVIEW

File: lib/nerves_ssh/options.ex [hunk 1]
```diff
@@ -245,7 +245,19 @@ defmodule NervesSSH.Options do
...
+    [system_dir: safe_dir(opts.system_dir), user_dir: safe_dir(opts.user_dir)]
+  end
+
+  defp safe_dir(dir) do
+    case File.mkdir_p(dir) do
+      :ok ->
+        to_charlist(dir)
+
+      {:error, err} ->
+        tmp = Path.join("/tmp", dir)
```
Comment (fhunleth) [inline lib/nerves_ssh/options.ex:257]:
```suggestion
        tmp = Path.join("/tmp/nerves_ssh", dir)
```

I added `nerves_ssh` to lower the chance of an unfortunate collision. I wasn't sure if `File.mkdir_p/1` needed to be called or if the daemon code would do that.

**Review by fhunleth — APPROVED** [review]
